spring:
  cloud:
    gateway:
      routes:
      - id: neo_route
        uri: http://www.google.com
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
        predicates:
        - Path=/test
